# Conda-forge friendly hmmer package.
# Targeting Apple Silicon (so we use the dev branch until official support is released)
package:
  name: hmmer
  version: "3.3.2.post0"

source:
  url: https://github.com/EddyRivasLab/hmmer/archive/182088b79cdc3248c1a2f42901795fa3004e92ab.zip
  sha256: 4abdd793d79cba8fc85aeead0dfc6486f2d89a83e9fd2764a2b9bc21a9b93f14

build:
  number: 0
  skip: True  # [not unix]

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  run:

test:
  commands:
    - alimask -h 2>&1 | grep "HMMER 3\." > /dev/null
    - hmmalign -h 2>&1 | grep "HMMER 3\." > /dev/null
    - hmmbuild -h 2>&1 | grep "HMMER 3\." > /dev/null
    - hmmconvert -h 2>&1 | grep "HMMER 3\." > /dev/null
    - hmmemit -h 2>&1 | grep "HMMER 3\." > /dev/null
    - hmmpress -h 2>&1 | grep "HMMER 3\." > /dev/null
    - hmmscan -h 2>&1 | grep "HMMER 3\." > /dev/null
    - hmmsearch -h 2>&1 | grep "HMMER 3\." > /dev/null
    - hmmsim -h 2>&1 | grep "HMMER 3\." > /dev/null
    - hmmstat -h 2>&1 | grep "HMMER 3\." > /dev/null
    - jackhmmer -h 2>&1 | grep "HMMER 3\." > /dev/null
    - phmmer -h 2>&1 | grep "HMMER 3\." > /dev/null
    - nhmmer -h 2>&1 | grep "HMMER 3\." > /dev/null
    - nhmmscan -h 2>&1 | grep "HMMER 3\." > /dev/null
    - hmmpgmd -h 2>&1 | grep "HMMER 3\." > /dev/null
    - esl-reformat -h 2>&1 | grep "Easel" > /dev/null

about:
  summary: Biosequence analysis using profile hidden Markov models
  home: http://hmmer.org/
  license: BSD
  license_file: LICENSE
