# Conda-forge friendly hmmer package.
# Targeting Apple Silicon (so we use the dev branch until official support is released)
# Based on the bioconda recipe. See:
#   https://bioconda.github.io/recipes/hmmer/README.html

package:
  name: hmmer
  version: "3.3.2.post0"

#
# As of 2022/11/19, develop branches of hmmer and easel have gone desynchronized
# Here we are using the latest develop tip of HMMER against an older develop tip of EASEL
# Pay attention and fix as soon as possible
#
source:
  - url: https://github.com/EddyRivasLab/hmmer/archive/182088b79cdc3248c1a2f42901795fa3004e92ab.zip
    sha256: 4abdd793d79cba8fc85aeead0dfc6486f2d89a83e9fd2764a2b9bc21a9b93f14
  - url: https://github.com/EddyRivasLab/easel/archive/1ee9e51ae6728bf62e931d50dd38e3a80a189e7b.zip
    sha256: 65435f872c385812e50d1681db2840fd52f14ca04f4cc22012946340291aca2e
    folder: easel

build:
  number: 0
  skip: True  # [not unix]

requirements:
  build:
    - gnuconfig
    - autoconf
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  run:

test:
  commands:
    - alimask -h 2>&1 | grep "HMMER 3\." > /dev/null
    - hmmalign -h 2>&1 | grep "HMMER 3\." > /dev/null
    - hmmbuild -h 2>&1 | grep "HMMER 3\." > /dev/null
    - hmmconvert -h 2>&1 | grep "HMMER 3\." > /dev/null
    - hmmemit -h 2>&1 | grep "HMMER 3\." > /dev/null
    - hmmpress -h 2>&1 | grep "HMMER 3\." > /dev/null
    - hmmscan -h 2>&1 | grep "HMMER 3\." > /dev/null
    - hmmsearch -h 2>&1 | grep "HMMER 3\." > /dev/null
    - hmmsim -h 2>&1 | grep "HMMER 3\." > /dev/null
    - hmmstat -h 2>&1 | grep "HMMER 3\." > /dev/null
    - jackhmmer -h 2>&1 | grep "HMMER 3\." > /dev/null
    - phmmer -h 2>&1 | grep "HMMER 3\." > /dev/null
    - nhmmer -h 2>&1 | grep "HMMER 3\." > /dev/null
    - nhmmscan -h 2>&1 | grep "HMMER 3\." > /dev/null
    - hmmpgmd -h 2>&1 | grep "HMMER 3\." > /dev/null
    - esl-reformat -h 2>&1 | grep "Easel" > /dev/null

about:
  summary: Biosequence analysis using profile hidden Markov models
  home: http://hmmer.org/
  license: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sdvillal